### ISSUE TITLE
Unable to install `python-build`; `UnsatisfiableError` in clean env but no further information

### ISSUE THREAD

**Issue by rawlins** [conda-forge/python-build-feedstock#13]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I cannot get `python-build` (or just `build`) to install from conda-forge, and the error is rather cryptic; it reports incompatible packages (`UnsatisfiableError`) but doesn't say what. This happens for me even in a completely clean env as you can see below. I suspect that this could conceivably have something to do with the fact that this is an M1 mac on Big Sur (`osx-arm64`), but as far as I can tell this package should work fine given that it's `noarch`. `build` installs and runs fine from pip. I haven't had any issues with other packages on this device and I've installed and I have plenty of noarch stuff successfully installed in various envs, which is why I'm opening the issue here, though it could still be more general.

Here's the full response to trying to install:

```
$ conda install python-build
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 

```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/advil/miniforge3/envs/cleantmp:
#
# Name                    Version                   Build  Channel
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : cleantmp
    active env location : /Users/advil/miniforge3/envs/cleantmp
            shell level : 2
       user config file : /Users/advil/.condarc
 populated config files : /Users/advil/miniforge3/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __osx=11.5.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/advil/miniforge3  (writable)
      conda av data dir : /Users/advil/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/advil/miniforge3/pkgs
                          /Users/advil/.conda/pkgs
       envs directories : /Users/advil/miniforge3/envs
                          /Users/advil/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.2 Darwin/20.6.0 OSX/11.5.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
It worked for me on Linux. Not sure what is going on there but this package is noarch so it should not really matter the OS :-/

**Comment by rawlins** [comment]
> It worked for me on Linux. Not sure what is going on there but this package is noarch so it should not really matter the OS :-/

Thanks, yes, I should've also mentioned that `python-build` installs just fine from conda-forge in a clean environment on an x86 mac that I have -- so I guess there must be something fairly specific about the situation on the device in my report that is leading to the symptoms. Though it's not a full apples to apples comparison in various ways (this other device is on Mojave still, and this [edit: the other device] isn't a miniforge setup).

**Comment by ocefpaf** [comment]
The failing one isn't miniforge? I thought it was based on your conda-info above. If it isn't be sure to add the conda-forge channel. I don't think build is in defaults yet.

**Comment by rawlins** [comment]
Yes, the failing one is miniforge. (The one that works isn't, but is using the conda-forge channel.)

**Comment by ocefpaf** [comment]
Oh. I completely missed that his is `osx-arm64`! Let me add the package for that arch.

**Comment by rawlins** [comment]
Great, thanks! Look like this got merged already. Not sure if that means it's available yet for me to test but I can try when I'm at my M1 machine this evening.

I guess the cryptic `UnsatisfiableError` was just a simple conflict with the arch, maybe with the virtual package `__archspec=1=arm64` then?

**Comment by ocefpaf** [comment]
Yep. The error message is not really user friendly. Note that the PR I merged just put it in the build queue. The bot will send a PR to it soon. I add M1 builds manually if the bot fails but I rather wait for it b/c it will build all the dependencies in order for us.

**Comment by rawlins** [comment]
This is working now for me on `osx-arm64`/M1 -- thanks for your help!!
