### ISSUE TITLE
What is this migration

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/python-build-feedstock#20]
### Comment:

I've noticed that https://github.com/conda-forge/pip-tools-feedstock/pull/32 PR has been open for a while.

Should it get pushed forward?

**Comment by henryiii** [comment]
It wouldn't be needed if #15 went in. Since the PyPI name is `build` and `build` on conda-forge can't be used for anything else, it seems perfectly fine to have this available as `build`, IMO.

**Comment by hmaarrfk** [comment]
Ok. It seems enough people with the power to move in one direction or the other are involved I'll stay out of it.

It seems that python-build would be easier to understand
